### ISSUE TITLE
a lot of small issues

### ISSUE THREAD

**Issue by Thrasilias** [Xitee1/PowerBoard#18]
looks like in a lot of classes u kinda forgot to add `{}`

**Comment by MrClean1337** [comment]
Please more infos, where for example?

**Comment by Xitee1** [comment]
The brackets are not always needed. If they aren't needed, I most of the time don't add them.

**Comment by Xitee1** [comment]
And as you can see, the code works and the IDE should not show any errors (At least that's the case in Eclipse).

**Comment by MrClean1337** [comment]
It is working normally and compiled normally.
Some if-cases just dont need {} if its a oneliner

**Comment by Thrasilias** [comment]
ah ok makes sense. i learned it a diffrent way lol. don't mind me then ;P
