### ISSUE TITLE
%player_ping% always is 0

### ISSUE THREAD

**Issue by FabiChan99** [Xitee1/PowerBoard#23]
%player_ping% always is 0 unless I reload the plugin.
I use 1.18.1

**Comment by Xitee1** [comment]
Does it work in other versions?
How long did you wait? It can take up to 5 minutes after joining the server to display the correct ping.

**Comment by FabiChan99** [comment]
Yes, this also happens on other versions and I also let it run for 20 mins. Its always 0

**Comment by FabiChan99** [comment]
Also it happens for every player

**Comment by Xitee1** [comment]
Just to be sure, you're not on a local server or similar?

**Comment by MrClean1337** [comment]
Sometimes it happens too, but as @Xitee1 said "It can take up to 5 minutes after joining the server to display the correct ping".

Got no problems 
![image](https://user-images.githubusercontent.com/58367170/198096750-d883d026-a986-479d-a3f9-3ea4e985113c.png)

**Comment by FabiChan99** [comment]
> Just to be sure, you're not on a local server or similar?

No its a Spigot Server thats hosted

**Comment by Xitee1** [comment]
Closing this issue because it can't be replicated.
It could be caused by a (wrong) proxy configuration, firewalls or something like that. The cause could be by the server hoster.
