### ISSUE TITLE
pex question

### ISSUE THREAD

**Issue by LuckyKuka** [Xitee1/PowerBoard#27]
Is PermissionsEX Permissions-System still available? Or is it deleted from code? How do I turn it on? I understand that no support will be given and blablabla (I am afraid of LuckPerms)

**Comment by Xitee1** [comment]
No, you have to search for an old version of PB. Go trough the change logs and you will somewhere find a change saying something like "removed pex" or "removed support for pex" (or permissionsex). I don't remember what version that was, but it was somewhere like 1 or 2 years ago.

However I would suggest you to just try out LuckPerms. With the web editor it is so easy to configurate and you have a nice overview.
I also stuck with PEX a long time after support end, but then I tried out LP and it is just so much better, modern and updated.

**Comment by LuckyKuka** [comment]
> No, you have to search for an old version of PB. Go trough the change logs and you will somewhere find a change saying something like "removed pex" or "removed support for pex" (or permissionsex). I don't remember what version that was, but it was somewhere like 1 or 2 years ago.
> 
> However I would suggest you to just try out LuckPerms. With the web editor it is so easy to configurate and you have a nice overview. I also stuck with PEX a long time after support end, but then I tried out LP and it is just so much better, modern and updated.

ok, I will try it, also I'll maybe try using luckperms, I have just saw on the internet that it is able to migrate from permissionsex to luckperms

**Comment by LuckyKuka** [comment]
it's very hard migration process and I won't remember this luckperms commands because i'm too lazy
so I am just going to use this «none» permissions system
