### ISSUE TITLE
[Suggestion] Prefix does not update in the tab

### ISSUE THREAD

**Issue by LuckyKuka** [Xitee1/PowerBoard#29]
So if I do something like this: /pex user <user> group set admin, then it does not update prefix in the tab, also %player_rank% does not update itself.

**Comment by LuckyKuka** [comment]
So much errors! I am just going to delete this freaking plugin! It annoys me! Author does not even want to fix them!

**Comment by Xitee1** [comment]
PEX is no longer supported. It only works with the "none" permission system. However this mode does not support automatic updating. The player has to rejoin to apply the new ranks.

**Comment by LuckyKuka** [comment]
> PEX is no longer supported. It only works with the "none" permission system. However this mode does not support automatic updating. The player has to rejoin to apply the new ranks.
Ok. then try to fix it , I think I will move to the tab plugin
