### ISSUE TITLE
How to turn off prompts to update player information in the background 

### ISSUE THREAD

**Issue by itwxb** [Xitee1/PowerBoard#38]
How to turn off prompts to update player information in the background 
 
like this
![Snipaste_2023-12-05_19-59-06](https://github.com/Xitee1/PowerBoard/assets/84020439/f776c8c3-04f5-49c1-83d3-49c4d039e435)

**Comment by Xitee1** [comment]
By disabling the debug mode.

**Comment by itwxb** [comment]
> By disabling the debug mode.通过禁用调试模式。

![Snipaste_2023-12-05_21-19-12](https://github.com/Xitee1/PowerBoard/assets/84020439/554f201f-3a8f-49ce-ba23-210d46281dd5)

is that?

**Comment by Xitee1** [comment]
Yes.

**Comment by itwxb** [comment]
> Yes.是的。

I set false but it still doesn't work, do I want to set it to true?

> Yes.
I set false but it still doesn't work, do I want to set it to true?

**Comment by Xitee1** [comment]
You need to set it to false to disable it.

What version are you using? I think you are using an outdated version. The message has changed some time ago and if I remember correctly, it was a bug in an old PowerBoard version that this message still showed when disabling debug mode.

**Comment by itwxb** [comment]
> You need to set it to false to disable it.您需要将其设置为 false 才能禁用它。
> 
> What version are you using? I think you are using an outdated version. The message has changed some time ago and if I remember correctly, it was a bug in an old PowerBoard version that this message still showed when disabling debug mode.您使用的是什么版本？我认为您使用的是过时的版本。该消息在一段时间前发生了变化，如果我没记错的话，这是旧PowerBoard版本中的一个错误，在禁用调试模式时仍然显示此消息。

I'm using version 3.5.11, if I want to upgrade to the latest version, I need to delete the old version of the plugin and folder, put in the new version of the plugin, and then I can rewrite the config

**Comment by itwxb** [comment]
> You need to set it to false to disable it.您需要将其设置为 false 才能禁用它。
> 
> What version are you using? I think you are using an outdated version. The message has changed some time ago and if I remember correctly, it was a bug in an old PowerBoard version that this message still showed when disabling debug mode.您使用的是什么版本？我认为您使用的是过时的版本。该消息在一段时间前发生了变化，如果我没记错的话，这是旧PowerBoard版本中的一个错误，在禁用调试模式时仍然显示此消息。

Or do I just need to delete the old plugin and put in the new plugin, and the file configuration will be updated automatically?

**Comment by Xitee1** [comment]
You can just replace the jar file on your server.
Depending on your server Minecraft version the configs should update automatically. If they don't update automatically you won't have access to newly added options in the config without manually adding them.

**Comment by itwxb** [comment]
> You can just replace the jar file on your server.您只需替换服务器上的 jar 文件即可。 Depending on your server Minecraft version the configs should update automatically. If they don't update automatically you won't have access to newly added options in the config without manually adding them.您只需替换服务器上的 jar 文件即可。 根据您的服务器Minecraft版本，配置应该会自动更新。如果它们没有自动更新，则如果不手动添加它们，您将无法访问配置中新添加的选项。

thanks!
