### ISSUE TITLE
Prefixes/suffixes of player tablist name don't seem to update with LuckPerms.

### ISSUE THREAD

**Issue by byteful** [Xitee1/PowerBoard#4]
The tablist name for any player doesn't seem to update with the new LuckPerms parent group.

So when I run /lp user <user> parent set <group>, it doesn't update in tablist.

I have to manually run /pb reload to apply the changes to the tablist.

Not sure if I configured something incorrectly, or if the plugin doesn't support this.

**Comment by Xitee1** [comment]
This issue is already known and it is on my todo list.

**Comment by Xitee1** [comment]
I tried to fix it but sadly I did not found a better LP event for it which triggers if a rank itself or a player's rank changes.
You can set the update interval in the PB config.yml to something like 1 or 2 so the ranks update all 1 or 2 seconds. There isn't a better way for this currently as far as I know.
