### ISSUE TITLE
The plugin reports errors in the console every once in a while.

### ISSUE THREAD

**Issue by Monutchuan** [Xitee1/PowerBoard#47]
**Describe the bug**
**Every once in a while, the console will pop up with a bunch of errors like the one in the picture. This may not affect normal use, but the console is filled with meaningless symbols.**
I think this is caused by the plug-in trying to check for updates but failing to obtain them, and the config.yml only provides two options of whether to notify players of updates or automatically update the plug-in, without the option of whether to allow the plug-in to check for updates. I hope this option will be added in 3.6.2.
_Moreover, in some countries or regions, because some networks are blocked, updates cannot be obtained normally, and you can only be forced to accept meaningless symbols._

**To Reproduce**
1. Launch the server.
2. Every once in a while this bunch of messages will appear.
...

**Screenshots**
![image](https://github.com/Xitee1/PowerBoard/assets/139550892/cd8e74c1-a189-415e-8d51-8e6b108125b1)

**Please complete the following information:**
 - Server version: Spigot 1.12.2
 - Plugin version 3.6.1

**Additional information**
Add more information that might help to solve the problem, e.g. your config.yml

**Comment by Xitee1** [comment]
You are right, I somehow haven't thought about that. I will definitely add this option to disable the update check completely. Probably I'll also make a pre-release so you can install that to prevent these errors 😄

**Comment by Xitee1** [comment]
Pre-release has been created.
You can download the jar here: https://github.com/Xitee1/PowerBoard/releases/tag/beta-3.6.2
