### ISSUE TITLE
Random playerkick: Team 749team-578 already exists in this scoreboard

### ISSUE THREAD

**Issue by MrClean1337** [Xitee1/PowerBoard#6]
Players get kicked random.

Related error logs:
Waterfall - waterfall-1.19-497
https://pastebin.com/raw/F5wShntp

Paper - git-Paper-36 (MC: 1.19)
https://pastebin.com/raw/f11C8mJF

Luckperms - v5.4.30

This happens if we do something luckperms related.
Then they will randomly kicked, like if we for example type `/lp user asdasdasd parent add premium` or `/powerboard reload`

**Comment by MrClean1337** [comment]
Still with the version v.3.5.13 not fixed:

https://pastebin.com/raw/xZ1nWG9q

**Comment by Xitee1** [comment]
[PowerBoard.zip](https://github.com/Xitee1/PowerBoard/files/9276437/PowerBoard.zip)
This could fix the problem. Please try if it does.

**Comment by MrClean1337** [comment]
> [PowerBoard.zip](https://github.com/Xitee1/PowerBoard/files/9276437/PowerBoard.zip) This could fix the problem. Please try if it does.

Hi, thank you it worked.
I downloaded the latest release from Powerboard and it looks like its working now :) 👍
